services:
  api:
    image: api:1.0
    build:
      context: ./api
      dockerfile: Dockerfile
    mem_limit: 0.5g
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
    
  lb:
    build:
      context: ./lb
      dockerfile: Dockerfile
    ports:
      - 8888:80
    depends_on:
      api: 
        condition: service_healthy

