services:
  web:
    build: ./web
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:9
    environment:
      MYSQL_DATABASE: demodb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test
    depends_on:
      db:
        condition: service_healthy
    
    
      